---
- hosts: webservers
  become: true
  gather_facts: yes

  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Display webserver IP from hostvars
      debug:
        msg: "Webserver IP: {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- hosts: dbservers
  become: true
  gather_facts: no # No need to gather facts for this example

  tasks:
    - name: Display a message
      debug:
        msg: "This task is running on a dbserver: {{ inventory_hostname }}"

    - name: Check if in check mode
      debug:
        msg: "Running in check mode!"
      when: ansible_check_mode